# =========================================================
# OPTICAL SYSTEM
# =========================================================
tx_diameter: 0.1
rx_diameter: 0.5

eta_tx: 0.8
eta_rx: 0.7
eta_misc: 0.9

wavelength: 8e-7
# =========================================================
# FIELD OF VIEW / FILTER
# =========================================================
fov: 0.000001
bandwidth: 0.000000001
condition: "day"   # "day" or "night"

# =========================================================
# ATMOSPHERE
# =========================================================
atmosphere:
  alpha_rayleigh_0: 5e-5
  alpha_aer_0: 3e-4
  alpha_humidity_0: 5e-5
  alpha_ozone_0: 5e-6
  angstrom_exponent: 1.3
  H_aer: 1200
  humidity: 0.5
  n_steps: 300

# =========================================================
# TURBULENCE
# =========================================================
turbulence:
  A: 0.00000000000005
  v: 21.0
  n_steps: 300
  model: "auto"

# =========================================================
# POINTING
# =========================================================
pointing:
  sigma_theta: 1e-6
  static_offset: 0.0

# =========================================================
# BACKGROUND (NUOVO)
# =========================================================
background:
  mie_g: 0.7
  angstrom: 1.3
  albedo: 0.3
  fluct_sigma: 0.25
clouds:
  p_clear_to_cloud: 0.003
  p_cloud_to_clear: 0.005
  min_loss_db: 20
  max_loss_db: 80
# =========================================================
# QKD
# =========================================================
mu: 0.5
e_opt: 0.02
